move_group:
  ros__parameters:
    interbotix_arm:
      kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
      kinematics_solver_search_resolution: 0.005
      kinematics_solver_timeout: 0.1
      kinematics_solver_attempts: 3
      # position_only_ik: true
    interbotix_gripper:
      kinematics_solver_search_resolution: 0.005
      kinematics_solver_timeout: 0.05
      kinematics_solver_attempts: 3
    # interbotix_gripper:
    #   kinematics_solver_search_resolution: 0.005
    #   kinematics_solver_timeout: 0.05
    #   kinematics_solver_attempts: 3
      # kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
      # kinematics_solver_search_resolution: 0.001
      # kinematics_solver_timeout: 0.1
      # position_only_ik: true

# move_group:
#   ros__parameters:
#     interbotix_arm:
#       kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
#       # optional parameters for caching:
#       max_cache_size: 10000
#       min_pose_distance: 0.005
#       min_joint_config_distance: 0.4
#     interbotix_gripper:
#       kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
#       # optional parameters for caching:
#       max_cache_size: 100
#       min_pose_distance: 1.0
#       min_joint_config_distance: 0.1

# move_group:
#   ros__parameters:
#     interbotix_arm:
#       kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
#       kinematics_solver_search_resolution: 0.01
#       kinematics_solver_timeout: 0.1
#       # position_only_ik: true
#     interbotix_gripper:
#       kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
#       kinematics_solver_search_resolution: 0.01
#       kinematics_solver_timeout: 0.1
#       # position_only_ik: true




# move_group:
#   ros__parameters:
#     interbotix_arm:
#       kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
#       kinematics_solver_search_resolution: 0.01
#       kinematics_solver_timeout: 0.005
#       position_only_ik: true
#     interbotix_gripper:
#       kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
#       kinematics_solver_search_resolution: 0.01
#       kinematics_solver_timeout: 0.005
#       position_only_ik: true

# move_group:
#   ros__parameters:
#     interbotix_arm:
#       kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
#       # optional parameters for caching:
#       max_cache_size: 10000
#       min_pose_distance: 1.0
#       min_joint_config_distance: 4.0
#     interbotix_gripper:
#       kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
#       # optional parameters for caching:
#       max_cache_size: 10000
#       min_pose_distance: 1.0
#       min_joint_config_distance: 4.0

