
use_sim_time: true 
num_iterations: 100
sleep_ms: 1000
action_scale: 3.0
world_frame: "world"
avoid_collisions: true
instruction: "pick up the top block on the stack"
translation_bound: 10.0
rotation_bound: 6.28
task_name: "pick_coke_can_high_fidelity"

## This file contains the configuration for the rt1_demo_app
# rt1_demo_app:
#   use_sim_time: {
#     type: bool,
#     default_value: true,
#     description: "Use simulation time"
#   }
#   num_iterations: {
#     type: int,
#     default_value: 100,
#     description: "Number of iterations to run the demo"
#   }
#   sleep_ms: {
#     type: int,
#     default_value: 100,
#     description: "Sleep time between iterations"
#   }
#   action_scale: {
#     type: double,
#     default_value: 1.0,
#     description: "Scale of the actions"
#   }
#   world_frame: {
#     type: string,
#     default_value: "world",
#     description: "Frame of the world"
#   }
#   avoid_collisions: {
#     type: bool,
#     default_value: true,
#     description: "Avoid collisions"
#   }
#   instruction: {
#     type: string,
#     default_value: "pick up the top block on the stack",
#     description: "Instruction to follow"
#   }

#