# camera extrinsics
# transformation from camera link to optical link [x y z qw qx qy qz]
trans_cam_opt: [0.0, 0.0, 0.0, 0.5, -0.5, 0.5, -0.5]

# transformation from base link to camera link [x y z qw qx qy qz]
# locobot:
trans_base_cam: [0.084, 0.017, 0.522, 0.916, 0.0, 0.401, 0.0]
# trans_base_cam: [0.084, 0.017, 0.522, 0.707, 0, 0.707, 0]
# trans_base_cam: [0, 0, 0., 0.921, 0.0, 0.3894, 0.0]

# when camera is to the right of the robot (cylinder)
# trans_base_cam: [0.0, -0.25, 0.04, 0.0, 0.0, 0.0, 0.0]
# when camera is in the overhead position
# trans_base_cam: [0.500, 0.000, 0.700, 0.707, 0.000, 0.707, 0.000]
